config/routes.rb
Rails.application.routes.draw do
  get 'tweets/index'

  get 'architecture/show'

  get 'home/show'

  root 'home#show'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  def avatar_url
    "http://placekitten.com/g/150/150"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/architecture_controller.rb
class ArchitectureController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = [
      Tweet.new(
        user_name: 'Eoin Kelly',
        user_handle: '@eoinkelly',
        body: 'hello there',
        favs: 1,
        retweets: 4),
      Tweet.new(
        user_name: 'John doe',
        user_handle: '@foo',
        body: 'hello everybody',
        favs: 4,
        retweets: 7)
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/architecture_helper.rb
module ArchitectureHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/architecture/show.html.erb
<h1>Important messages</h1>

<div class="message">
  <div class="content">
    I am an important update from some online service that you don't
    remember signing up for. I demand you take action immediately.
  </div>
  <button class="btn">Dismiss</button>
  <button class="btn btn-alert">Mark as important</button>
  <button class="btn btn-info">Like</button>
</div>

app/views/home/show.html.erb
<h1>Welcome frontend streamers</h1>


<ul>
  <li>
    <%= link_to "Open architecture example", architecture_show_path %>
  </li>
  <li>
    <%= link_to "Open twitter example", tweets_index_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FrontendStreamers</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1>Tweets</h1>

<p>
Welcome to twitterer - a simple twitter website that shows you the tweets for lots of important people
</p>

<div class="tweets">
  <% @tweets.each do |tweet| %>
    <div class="tweet">
      <div class="avatar">
        <%= image_tag tweet.avatar_url %>
      </div>
      <div class="header">
        <div class="name">
          <%= tweet.user_name %>
        </div>
        <div class="handle">
          <%= tweet.user_handle %>
        </div>
      </div>
      <div class="body">
        <div class="actions">
          <div class="reply">
            <button>Reply</button>
          </div>
          <div class="retweets">
            <%= tweet.retweets %>
          </div>
          <div class="favs">
            <%= tweet.favs %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>